import { useCallback, useEffect, useState } from 'react';
import { CalendarDays, CheckCircle2, ClipboardList, HeartPulse, LogOut, Menu, ShieldCheck, Stethoscope, UserRound, Users, X } from 'lucide-react';
import { apiRequest } from '../services/api.js';
import './DashboardPage.css';

const roleCopy={patient:['Patient dashboard',UserRound],doctor:['Doctor dashboard',Stethoscope],admin:['Administration',ShieldCheck]};
export default function DashboardPage({expectedRole}){
 const [user,setUser]=useState(null),[error,setError]=useState(''),[summary,setSummary]=useState(null),[pending,setPending]=useState([]),[menu,setMenu]=useState(false),[message,setMessage]=useState('');
 const load=useCallback(async()=>{try{const profile=await apiRequest('/auth/me');if(profile.user.role!==expectedRole)throw new Error('This dashboard does not match your account role');setUser(profile.user);if(expectedRole==='admin'){const data=await apiRequest('/admin/summary');setSummary(data.summary);setPending(data.pendingDoctors)}}catch(e){setError(e.message)}},[expectedRole]);
 useEffect(()=>{const timer=window.setTimeout(load,0);return()=>window.clearTimeout(timer)},[load]);
 async function logout(){await apiRequest('/auth/logout',{method:'POST'});window.location.hash='home'}
 async function approve(id){try{const r=await apiRequest(`/admin/doctors/${id}/approve`,{method:'PATCH'});setMessage(r.message);await load()}catch(e){setMessage(e.message)}}
 async function changePassword(e){e.preventDefault();const d=new FormData(e.currentTarget);if(d.get('newPassword')!==d.get('confirmPassword')){setMessage('New passwords do not match');return}try{const r=await apiRequest('/auth/password',{method:'PATCH',body:JSON.stringify({currentPassword:d.get('currentPassword'),newPassword:d.get('newPassword')})});setMessage(r.message);e.currentTarget.reset()}catch(err){setMessage(err.message)}}
 if(error)return <main className="dashboard-state"><ShieldCheck/><h1>Access unavailable</h1><p>{error}</p><a href={`#${expectedRole}-login`}>Return to login</a></main>;
 if(!user)return <main className="dashboard-state"><HeartPulse className="dashboard-pulse"/><p>Loading your secure dashboard…</p></main>;
 const RoleIcon=roleCopy[expectedRole][1];
 return <main className={`dashboard dashboard--${expectedRole}`}><aside className={menu?'open':''}><a href="#home" className="dashboard-brand"><HeartPulse/><strong>People’s Clinic</strong></a><nav><button className="active"><ClipboardList/>Overview</button><button><CalendarDays/>Appointments</button><button><UserRound/>Profile</button><button><ShieldCheck/>Security</button></nav><button className="dashboard-logout" onClick={logout}><LogOut/>Logout</button></aside><section className="dashboard-main"><header><button className="dashboard-menu" onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</button><div><p>{roleCopy[expectedRole][0]}</p><h1>Welcome, {user.fullName}</h1></div><span className="dashboard-avatar"><RoleIcon/></span></header><div className="dashboard-grid"><article className="dashboard-hero-card"><span><RoleIcon/></span><div><p>Signed in as {expectedRole}</p><h2>{expectedRole==='patient'?'Your health, organized in one place.':expectedRole==='doctor'?'Your clinical day at a glance.':'Clinic operations and approvals.'}</h2><small>{user.email}</small></div></article>{expectedRole==='patient'&&<><article><CalendarDays/><b>Upcoming appointments</b><strong>0</strong><small>Your confirmed visits will appear here.</small></article><article><ClipboardList/><b>Health records</b><strong>Secure</strong><small>Reports, bills, and visit history.</small></article></>}{expectedRole==='doctor'&&<><article><CalendarDays/><b>Today’s appointments</b><strong>0</strong><small>Your approved schedule will appear here.</small></article><article><Users/><b>Patients today</b><strong>0</strong><small>Patient visit details and notes.</small></article></>}{expectedRole==='admin'&&summary&&Object.entries(summary).map(([k,v])=><article key={k}><Users/><b>{k}</b><strong>{v}</strong><small>Current clinic total</small></article>)}</div>{expectedRole==='admin'&&<section className="dashboard-table"><h2>Pending doctor approvals</h2>{pending.length?pending.map(d=><div key={d._id}><span><b>{d.fullName}</b><small>{d.email} · {d.phone}</small></span><button onClick={()=>approve(d._id)}><CheckCircle2/>Approve</button></div>):<p>No doctor accounts are waiting for approval.</p>}</section>}<section className="dashboard-security"><h2>Change password</h2><form onSubmit={changePassword}><input name="currentPassword" type="password" placeholder="Current password" required/><input name="newPassword" type="password" placeholder="New password" minLength="8" required/><input name="confirmPassword" type="password" placeholder="Confirm new password" minLength="8" required/><button>Update password</button></form>{message&&<p>{message}</p>}</section></section></main>}
