import { useCallback, useEffect, useState } from 'react';
import { ArrowUp, BellRing, Check, Clock3, Download, FileHeart, Pencil, Pill, Plus, RefreshCw, Trash2, X } from 'lucide-react';
import { apiRequest } from '../services/api.js';
import { printPrescription } from '../utils/prescription-print.js';
import MedicalSummary from '../components/MedicalSummary.jsx';
import { printMedicalSummary } from '../utils/summary-print.js';
import './MedicationPanel.css';
import './MedicationActions.css';
import './CarePlans.css';

const doseLabels = { morning: 'Morning', afternoon: 'Afternoon', evening: 'Evening', night: 'Night' };

export function HealthSummaryPanel() {
  const [reports,setReports]=useState([]),[error,setError]=useState(''),[message,setMessage]=useState('');
  useEffect(()=>{apiRequest('/medical-reports').then(data=>setReports((data.reports||[]).filter(report=>report.summaryStatus==='ready'))).catch(err=>setError(err.message))},[]);
  async function share(report){if(report.sharedWithDoctor)return;setError('');try{const data=await apiRequest(`/medical-reports/${report._id}/share`,{method:'PATCH'});setReports(current=>current.map(item=>item._id===report._id?data.report:item))}catch(err){setError(err.message)}}
  async function remove(report){if(!window.confirm(`Remove ${report.title} permanently?`))return;setError('');try{const data=await apiRequest(`/medical-reports/${report._id}`,{method:'DELETE'});setReports(current=>current.filter(item=>item._id!==report._id));setMessage(data.message)}catch(err){setError(err.message)}}
  return <article className="dash-panel module-live health-summary-panel"><FileHeart/><h2>AI health summary</h2><p>AI-generated findings are assistance only and should be reviewed by a qualified doctor.</p>{message&&<p className="dash-sync-message"><Check/>{message}</p>}{error&&<p className="report-error">{error}</p>}{reports.map(report=><div key={report._id}><div className="health-summary-card__head"><span><b>{report.title}</b><small>{report.sharedWithDoctor?'Shared':'Private to you'}</small></span><div><button className="summary-share-icon" type="button" disabled={report.sharedWithDoctor} onClick={()=>share(report)} title={report.sharedWithDoctor?'Shared with doctor':'Share summary with doctor'} aria-label={report.sharedWithDoctor?'Shared with doctor':'Share summary with doctor'}>{report.sharedWithDoctor?<Check/>:<ArrowUp/>}</button><button type="button" onClick={()=>printMedicalSummary(report)}><Download/>Download</button><button type="button" className="summary-remove" onClick={()=>remove(report)}><Trash2/>Remove</button></div></div><MedicalSummary summary={report.aiSummary}/>{report.keyFindings?.length>0&&<ul>{report.keyFindings.map(finding=><li key={finding}>{finding}</li>)}</ul>}</div>)}{!reports.length&&!error&&<div><b>No AI summaries yet</b><span>Upload a report under Health records to generate your first summary.</span></div>}</article>;
}

export function PrescriptionPanel() {
  const [consultations,setConsultations]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{apiRequest('/consultations/mine').then(data=>setConsultations(data.consultations||[])).catch(err=>setError(err.message)).finally(()=>setLoading(false))},[]);
  return <article className="dash-panel module-live prescription-panel"><div className="dash-panel__head"><div><h2>My prescriptions</h2><p>Doctor-issued prescriptions and visit instructions are kept separately from your daily medication tracker.</p></div><FileHeart/></div>{error&&<p className="report-error">{error}</p>}{loading&&<div className="dash-empty"><RefreshCw className="spinning"/><b>Loading prescriptions</b></div>}<section className="care-plan-list">{consultations.map(item=><article key={item._id}><div><b>{item.doctorName}</b><small>{item.bookingId} · {item.status}</small></div>{item.clinicalNotes&&<p><strong>Advice:</strong> {item.clinicalNotes}</p>}{item.recommendedTests&&<p><strong>Tests:</strong> {item.recommendedTests}</p>}{item.prescriptions?.length>0&&<div className="patient-prescription-lines">{item.prescriptions.map(medicine=><span key={`${medicine.medicineName}-${medicine.dosage}`}><b>{medicine.medicineName}</b><small>{medicine.dosage} · {medicine.times?.join(', ')} · {medicine.durationDays} days{medicine.instructions?` · ${medicine.instructions}`:''}</small></span>)}</div>}{item.nextVisitDate&&<p><strong>Next visit:</strong> {new Date(`${item.nextVisitDate}T00:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}</p>}<button type="button" className="patient-prescription-download" onClick={()=>printPrescription(item)}>Download prescription PDF</button></article>)}</section>{!loading&&!consultations.length&&<div className="dash-empty"><FileHeart/><b>No doctor prescriptions yet</b><p>Prescriptions sent after a consultation will appear here automatically.</p></div>}<button className="prescription-upload-link" type="button" onClick={()=>window.dispatchEvent(new CustomEvent('patient-dashboard-open',{detail:'records'}))}>Upload a prescription document</button></article>;
}

function MedicationForm({ medication, today, onSave, onClose, onDelete }) {
  const selectedTimes=new Set(medication?.times||[]);
  return <form className="medicine-form" onSubmit={onSave}>
    <label>Medicine name<input name="medicineName" defaultValue={medication?.medicineName||''} placeholder="Medicine name" required/></label>
    <label>Dosage<input name="dosage" defaultValue={medication?.dosage||''} placeholder="For example: 5 mg" required/></label>
    <label>Priority<select name="priority" defaultValue={medication?.priority||'routine'}><option value="routine">Routine</option><option value="important">Important</option><option value="urgent">Urgent</option></select></label>
    <fieldset><legend>Schedule</legend>{Object.entries(doseLabels).map(([value,label])=><label key={value}><input type="checkbox" name="times" value={value} defaultChecked={selectedTimes.has(value)}/>{label}</label>)}</fieldset>
    <label>Start date<input name="startDate" type="date" defaultValue={medication?.startDate||today} required/></label>
    <label>End date<input name="endDate" type="date" defaultValue={medication?.endDate||''}/></label>
    <label className="medicine-form__wide">Instructions<input name="instructions" defaultValue={medication?.instructions||''} placeholder="After food, before sleep, etc."/></label>
    <div className="medicine-form__actions"><button type="submit">{medication?'Save changes':'Add schedule'}</button><button type="button" onClick={onClose}>Cancel</button>{medication&&<button type="button" className="delete-medicine" onClick={()=>onDelete(medication)}><Trash2/>Remove medicine</button>}</div>
  </form>;
}

export default function MedicationPanel() {
  const [medications,setMedications]=useState([]),[loading,setLoading]=useState(true),[adding,setAdding]=useState(false),[editing,setEditing]=useState(null),[message,setMessage]=useState(''),[error,setError]=useState('');
  const localDateKey=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
  const today=localDateKey(new Date());
  const load=useCallback(async()=>{setLoading(true);setError('');try{const medicineData=await apiRequest('/medications');setMedications(medicineData.medications||[])}catch(err){setError(err.message)}finally{setLoading(false)}},[]);
  useEffect(()=>{const initial=window.setTimeout(load,0);const timer=window.setInterval(load,10000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[load]);
  async function saveMedication(event){event.preventDefault();setError('');const form=new FormData(event.currentTarget);const payload={medicineName:form.get('medicineName'),dosage:form.get('dosage'),times:form.getAll('times'),instructions:form.get('instructions'),priority:form.get('priority'),startDate:form.get('startDate'),endDate:form.get('endDate')};try{const data=await apiRequest(editing?`/medications/${editing._id}`:'/medications',{method:editing?'PUT':'POST',body:JSON.stringify(payload)});setMedications(current=>editing?current.map(item=>item._id===editing._id?data.medication:item):[data.medication,...current]);setMessage(data.message);setAdding(false);setEditing(null)}catch(err){setError(err.message)}}
  async function removeMedication(medication){if(!window.confirm(`Remove ${medication.medicineName} from your medication list?`))return;setError('');try{const data=await apiRequest(`/medications/${medication._id}`,{method:'DELETE'});setMedications(current=>current.filter(item=>item._id!==medication._id));setMessage(data.message);if(editing?._id===medication._id)setEditing(null)}catch(err){setError(err.message)}}
  async function mark(medication,time,status){try{const data=await apiRequest(`/medications/${medication._id}/doses`,{method:'PATCH',body:JSON.stringify({date:today,time,status})});setMedications(current=>current.map(item=>item._id===medication._id?data.medication:item));setMessage(data.message)}catch(err){setError(err.message)}}
  async function enableNotifications(){if(!('Notification' in window)){setError('This browser does not support medicine notifications');return}const permission=await Notification.requestPermission();if(permission==='granted'){new Notification("People's Clinic medicine reminder",{body:'Medicine reminders are enabled for this browser.'});setMessage('Medicine notifications enabled')}else setError('Notification permission was not granted')}
  const doseStatus=(medication,time)=>medication.doseLogs?.find(log=>log.date===today&&log.time===time)?.status||'pending';
  const pendingCount=medications.reduce((count,item)=>count+item.times.filter(time=>doseStatus(item,time)==='pending').length,0);
  const takenCount=medications.reduce((count,item)=>count+item.times.filter(time=>doseStatus(item,time)==='taken').length,0),missedCount=medications.reduce((count,item)=>count+item.times.filter(time=>doseStatus(item,time)==='missed').length,0),scheduledCount=takenCount+missedCount+pendingCount;
  const closeForm=()=>{setAdding(false);setEditing(null)};
  return <article className="dash-panel module-live medicine-panel">
    <div className="dash-panel__head"><div><h2>Medication manager</h2><p>Add or edit schedules and record every daily dose.</p></div><div className="medicine-head-actions"><button type="button" onClick={enableNotifications}><BellRing/>Enable reminders</button><button type="button" onClick={()=>{setEditing(null);setAdding(value=>!value)}}><Plus/>{adding&&!editing?'Close':'Add medicine'}</button></div></div>
    <div className="medicine-alert"><Clock3/><div><b>{pendingCount} dose{pendingCount===1?'':'s'} waiting today</b><span>Mark each dose Taken or Missed so your history remains accurate.</span></div></div>
    {(adding||editing)&&<MedicationForm key={editing?._id||'new'} medication={editing} today={today} onSave={saveMedication} onClose={closeForm} onDelete={removeMedication}/>} 
    {message&&<p className="dash-sync-message"><Check/>{message}</p>}{error&&<p className="report-error">{error}</p>}
    <div className="medicine-list">{medications.map(medication=><section className={`medicine-card priority-${medication.priority}`} key={medication._id}>
      <div className="medicine-card__title"><span><Pill/></span><div><h3>{medication.medicineName}</h3><p>{medication.dosage}{medication.instructions?` · ${medication.instructions}`:''}</p></div><span className="medicine-card__badge"><em>{medication.priority}</em><button type="button" aria-label={`Edit ${medication.medicineName}`} title="Edit medicine" onClick={()=>{setAdding(false);setEditing(medication)}}><Pencil/></button></span></div>
      <div className="dose-grid">{medication.times.map(time=>{const status=doseStatus(medication,time);return <div className={`dose dose-${status}`} key={time}><div><Clock3/><b>{doseLabels[time]}</b><small>{status}</small></div><button type="button" onClick={()=>mark(medication,time,'taken')} className="take"><Check/>Taken</button><button type="button" onClick={()=>mark(medication,time,'missed')} className="miss"><X/>Missed</button></div>})}</div>
      <small className="medicine-source">{medication.source==='manual'?'Added manually':'Synchronized from prescription'}</small>
    </section>)}{!loading&&!medications.length&&<div className="dash-empty"><Pill/><b>No medication schedules</b><p>Add a medicine to start tracking doses.</p></div>}{loading&&<div className="dash-empty"><RefreshCw className="spinning"/><b>Loading medication schedule</b></div>}</div>
    <section className="medicine-stats" aria-label="Medication statistics"><div><b>{medications.length}</b><span>Active medicines</span></div><div><b>{scheduledCount}</b><span>Scheduled today</span></div><div className="stat-taken"><b>{takenCount}</b><span>Taken</span></div><div className="stat-missed"><b>{missedCount}</b><span>Missed</span></div><div><b>{pendingCount}</b><span>Pending</span></div></section>
    <section className="adherence-chart"><div><h3>Seven-day adherence</h3><p>Taken and missed doses remain in history while today resets automatically at midnight.</p></div><div className="adherence-bars">{Array.from({length:7},(_,index)=>{const date=new Date();date.setDate(date.getDate()-(6-index));const key=localDateKey(date);const logs=medications.flatMap(item=>item.doseLogs||[]).filter(log=>log.date===key);const taken=logs.filter(log=>log.status==='taken').length,missed=logs.filter(log=>log.status==='missed').length,total=Math.max(1,taken+missed);return <span key={key}><i><b style={{height:`${taken/total*100}%`}}/><em style={{height:`${missed/total*100}%`}}/></i><small>{date.toLocaleDateString('en',{weekday:'short'})}</small></span>})}</div><div className="adherence-legend"><span><i/>Taken</span><span><i/>Missed</span></div></section>
  </article>;
}
